Repository wizaplace/wizaplace-php-sdk, pull requests merged in 2018-08, with the labels that each got.

#320 Add method to get a list of Product instead of ProductSummary
  src/Catalog/CatalogService.php
  src/Catalog/CatalogServiceInterface.php
  tests/Catalog/CatalogServiceTest.php
Labels: WIP

#318 5863 organisation sdk
  CHANGELOG.md
  src/ArrayableInterface.php
  src/Exception/UserDoesntBelongToOrganisation.php
  src/Organisation/Organisation.php
  src/Organisation/OrganisationAddress.php
  src/Organisation/OrganisationAdministrator.php
  src/Organisation/OrganisationFile.php
  src/Organisation/OrganisationService.php
  tests/Organisation/OrganisationServiceTest.php
  tests/Organisation/OrganisationServiceTest/testAddBasket.yml
  tests/Organisation/OrganisationServiceTest/testBasketValidation.yml
  tests/Organisation/OrganisationServiceTest/testCannotAddBasketIfNotOwned.yml
  tests/Organisation/OrganisationServiceTest/testCannotGetListIfNotOwned.yml
  tests/Organisation/OrganisationServiceTest/testCannotGetListUsersIfNotOwned.yml
  tests/Organisation/OrganisationServiceTest/testCannotGetOrganisationIfNotOwned.yml
  tests/Organisation/OrganisationServiceTest/testCannotLockBasketIfNotOwned.yml
  tests/Organisation/OrganisationServiceTest/testCannotRegisterIfAlreadyLogged.yml
  tests/Organisation/OrganisationServiceTest/testCannotUpdateOrganisationAddresses.yml
  tests/Organisation/OrganisationServiceTest/testCannotUpdateOrganisationIfNotOwned.yml
  tests/Organisation/OrganisationServiceTest/testCannotValidateBasketIfNotOwned.yml
  tests/Organisation/OrganisationServiceTest/testGetList.yml
  tests/Organisation/OrganisationServiceTest/testGetListUsers.yml
  tests/Organisation/OrganisationServiceTest/testGetOrganisation.yml
  tests/Organisation/OrganisationServiceTest/testLockBasket.yml
  tests/Organisation/OrganisationServiceTest/testOrganisationAddressesUpdate.yml
  tests/Organisation/OrganisationServiceTest/testOrganisationUpdate.yml
  tests/Organisation/OrganisationServiceTest/testRegisterWithAdminUser.yml
  tests/Organisation/OrganisationServiceTest/testRegisterWithUnauthenticatedUser.yml
  tests/Vendor/Promotion/BasketPromotionServiceTest.php
  tests/Vendor/Promotion/BasketPromotionServiceTest/testPromotionLifeCycle.yml
  tests/Vendor/Promotion/CatalogPromotionServiceTest.php
  tests/Vendor/Promotion/CatalogPromotionServiceTest/testPromotionLifeCycle.yml
Labels: enhancement

#325 add missing parameter to some \Exception
  src/Organisation/OrganisationService.php
Labels: bug
