Repository wizaplace/wizaplace-php-sdk, pull requests merged in 2019-05, with the labels that each got.

#466 WIZ-700 Add lastStatusChange property to Order
  CHANGELOG.md
  src/Vendor/Order/Order.php
  src/Vendor/Order/OrderSummary.php
  tests/Vendor/Order/OrderServiceTest.php
  tests/Vendor/Order/OrderServiceTest/testDenormalizeLastStatusChange with data set #0.yml
  tests/Vendor/Order/OrderServiceTest/testDenormalizeLastStatusChange with data set #1.yml
  tests/Vendor/Order/OrderServiceTest/testDenormalizeLastStatusChange with data set #2.yml
  tests/Vendor/Order/OrderServiceTest/testDenormalizeLastStatusChange with data set #3.yml
  tests/Vendor/Order/OrderServiceTest/testDenormalizeLastStatusChange with data set #4.yml
  tests/Vendor/Order/OrderServiceTest/testDenormalizeLastStatusChange with data set #5.yml
  tests/Vendor/Order/OrderServiceTest/testDenormalizeLastStatusChange with data set #6.yml
  tests/Vendor/Order/OrderServiceTest/testGetOrderById.yml
  tests/Vendor/Order/OrderServiceTest/testListOrders.yml
Labels: P: High

#474 WIZ-680 add filters to orders api
  CHANGELOG.md
  src/Vendor/Order/OrderListFilter.php
  src/Vendor/Order/OrderService.php
  tests/Vendor/Order/OrderServiceTest.php
  tests/Vendor/Order/OrderServiceTest/testFilterByCompanyIdWithAResult.yml
  tests/Vendor/Order/OrderServiceTest/testFilterByCompanyIdWithNoResult.yml
  tests/Vendor/Order/OrderServiceTest/testFilterByLastStatusChange.yml
Labels: P: High

#486 WIZ-3092 Update DiscussionService/submitContactRequest (3 opt params)
  CHANGELOG.md
  src/Discussion/DiscussionService.php
  tests/Discussion/DiscussionServiceTest.php
  tests/Discussion/DiscussionServiceTest/testSubmitContactRequest.yml
  tests/Discussion/DiscussionServiceTest/testSubmitContactRequestWithAttachments.yml
Labels: P: Urgent

#481 WIZ-990 Add IBAN and BIC properties to unauthenticatedRegister()
  CHANGELOG.md
  src/Company/CompanyService.php
  tests/Company/CompanyServiceTest.php
  tests/Company/CompanyServiceTest/testRegisterACompanyWithIbanAndBicUnauthenticated.yml
  tests/Company/CompanyServiceTest/testRegisteringACompanyUnauthenticated.yml
Labels: P: Urgent, To merge

#506 WIZ-3338 Company::__construct with NAF Code null in constructor
  CHANGELOG.md
  src/Company/Company.php
  tests/Company/CompanyServiceTest.php
  tests/Company/CompanyServiceTest/testRegisterACompanyWithReturnNafCodeNull.yml
Labels: P: Urgent

#507 WIZ-3014 Fix missing Order Status
  CHANGELOG.md
  src/Order/OrderStatus.php
  src/Vendor/Order/OrderStatus.php
  tests/Vendor/Order/OrderServiceTest.php
  tests/Vendor/Order/OrderServiceTest/testGetOrderWithStatus with data set #0.yml
  tests/Vendor/Order/OrderServiceTest/testGetOrderWithStatus with data set #1.yml
  tests/Vendor/Order/OrderServiceTest/testGetOrderWithStatus with data set #2.yml
Labels: P: Urgent
